name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]    # run on pushes to the main branch (adjust if your default branch is master)
  workflow_dispatch:      # allow manual trigger if needed

permissions:
  contents: read          # allow read access to repo contents (for checkout)
  pages: write            # allow publishing to Pages
  id-token: write         # allow OIDC token for deploy-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"        # Use a Ruby version compatible with your gems
          bundler-cache: true        # Cache and install gems automatically:contentReference[oaicite:8]{index=8}

      - name: Setup Pages config
        id: pages
        uses: actions/configure-pages@v3

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: "production"
        # The --baseurl uses the Pages output path (empty for user sites, or "/repoName" for project sites)

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v1
        # This step collects the _site output for deployment

  deploy:
    runs-on: ubuntu-latest
    needs: build               # wait for the 'build' job to complete
    environment:
      name: github-pages       # target the GitHub Pages environment
      url: ${{ steps.deployment.outputs.page_url }}  # the deployed site URL (after deployment)
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
